### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [webplate/chronogeoscope_cordova#1]
Hi,

Since this app is CC-BY-NC-SA licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by webplate** [comment]
Hello Poussinou !

I like your moto "I may be slow to respond." And I respond five years later :) It is absolutely OK to put the app on the F-Droid store. Anyone who knows how to do it is encouraged. The app isn't maintained (sorry I have no spare time for this) and I don't know if it works well on modern android.

Thank you for your comment, and please do not use my software to justify flat earth theories :D

**Comment by webplate** [comment]
Out of curiosity: how did you find this app ?

**Comment by Poussinou** [comment]
Hi,

Not gonna blame you lol xD

Can't even remember how I found this repo. I spend some time to find apps on GitHub that may be interesting to include in F-Droid from time to time since years. This one is something unique, I thought it could be interesting for some people, just for the curiosity (like [this app](https://f-droid.org/packages/de.vanitasvitae.enigmandroid/) for example).

We usually don't include old unmaintained apps in the official as it is obviously bad practice. What you could do is include an apk in the [release section](https://github.com/webplate/chronogeoscope_cordova/releases) and write in the README.md that people can download your app in this release section. If you currently don't have an apk available, just keep the repo as it is, the website is still working properly :)

Cheers!

**Comment by webplate** [comment]
Thanks for sharing the Enigma App :D And for the advice.

The [Chronogeoscope website](https://lambda.casa/chronogeoscope/) is indeed the preferred version of the software.
